[teddit]
# Possible values can be found in the settings of the teddit instance.
instance = 'teddit.pussthecat.org'

theme = 'dark'
flairs = true
nsfw_enabled = true
highlight_controversial = true
post_media_max_height = 'medium'
collapse_child_comments = false
show_upvoted_percentage = true
show_upvotes = true
videos_muted = true
domain_twitter = ''
domain_youtube = ''
domain_instagram = ''
prefer_frontpage = true
default_comment_sort = 'best'
show_large_gallery_images = 'undefined'

[reddit]
subscriptions = [
    '3kliksphilip',
    'aaaaaaacccccccce',
    'AbandonedPorn',
    'ABoringDystopia',
    'Absurdism',
    'admincraft',
    'ainbow',
    'AlternateAngles',
    'AnarchyChess',
    'AnimalPorn',
    'anime_titties',
    'anthro',
    'Anticonsumption',
    'ApocalypsePorn',
    'archlinux',
    'arduino',
    'ArduinoProjects',
    'ARG',
    'arkisuomi',
    'arma',
    'AskEurope',
    'AskScience',
    'behindthephoto',
    'bestoflegaladvice',
    'bi_irl',
    'bicycling',
    'bigsleep',
    'birb',
    'Birbs',
    'Birbsloveseed',
    'birding',
    'birdpics',
    'birds',
    'bisexual',
    'borbs',
    'bottom_irl',
    'boypussy',
    'cableporn',
    'CatastrophicFailure',
    'classicube',
    'cockatiel',
    'Conures',
    'CoolAmericaFacts',
    'coolgithubprojects',
    'CrackWatch',
    'CraftedMovie',
    'crowbro',
    'crows',
    'css_irl',
    'cutegayshit',
    'Cyberpunk',
    'cybersecurity',
    'DarkNaturalism',
    'data_irl',
    'DataHoarder',
    'dataisbeautiful',
    'dataisugly',
    'Deltarune',
    'DinosaurAncestry',
    'Discord_Bots',
    'discord_irl',
    'disneyvacation',
    'egg_irl',
    'EiOleLehti',
    'EngineeringPorn',
    'europe',
    'EverythingFoxes',
    'explainlikeimfive',
    'feedthebeast',
    'feedthememes',
    'feedthetraa',
    'femboy_irl',
    'feminineboys',
    'ferrets',
    'fifthworldproblems',
    'Finches',
    'findareddit',
    'Finland',
    'firefox',
    'FirefoxCSS',
    'flessedimages',
    'foxes',
    'foxfanclub',
    'FreeGameFindings',
    'fuckcars',
    'functionalprint',
    'FurFoxSake',
    'furrealmemes',
    'furry',
    'furry_irl',
    'furrydiscuss',
    'furrymemes',
    'furrypasta',
    'FurryPeopleTwitter',
    'FurryVisualNovels',
    'fursedimages',
    'fursuit',
    'futureporn',
    'Futurology',
    'gamedev',
    'GamePhysics',
    'Gamingcirclejerk',
    'GamingDetails',
    'GamingLeaksAndRumours',
    'GaySoundsShitposts',
    'GeometryIsNeat',
    'GlobalOffensive',
    'GlobalOffensiveLinux',
    'hackernews',
    'hardwaregore',
    'Hasan_Piker',
    'HellscapePorn',
    'hiddenrooms',
    'HistoryMemes',
    'homelab',
    'HomeServer',
    'honeyfuckers',
    'HytaleInfo',
    'IcebergCharts',
    'IdiotsInCars',
    'illegallifeprotips2',
    'illegallysmolbirbs',
    'ImaginaryBestOf',
    'ImaginaryHorrors',
    'ImaginaryMindscapes',
    'ImaginaryWastelands',
    'ImaginaryWeather',
    'InfrastructurePorn',
    'itrunsdoom',
    'ItsHipToFuckBees',
    'Joensuu',
    'Justrolledintotheshop',
    'KoboldLegion',
    'LateStageCapitalism',
    'LateStageGenderBinary',
    'leftistvexillologycj',
    'leopardgeckos',
    'LeopardsAteMyFace',
    'lgbt',
    'LifeProTips',
    'linkiscute',
    'LinusTechTips',
    'linux',
    'linux_gaming',
    'linuxmasterrace',
    'linuxmemes',
    'LinuxYiff',
    'LiveOverflow',
    'LivestreamFail',
    'lostmedia',
    'LucidDreaming',
    'MapPorn',
    'mapporncirclejerk',
    'masterhacker',
    'me_irlgbt',
    'medievaldoctor',
    'MensLib',
    'mina_irl',
    'Miniworlds',
    'MirrorsEdgeAesthetics',
    'mobilephotography',
    'morbidquestions',
    'MovieDetails',
    'NatureIsFuckingCute',
    'NatureIsFuckingLit',
    'natureismetal',
    'netsec',
    'Nordichistorymemes',
    'NoStupidQuestions',
    'notdisneyvacation',
    'nottheonion',
    'oddlyterrifying',
    'okbuddycapitalist',
    'okbuddychicanery',
    'okbuddyhasan',
    'okbuddyhetero',
    'okbuddyimperialist',
    'okbuddylinux',
    'okbuddymonstercat',
    'okbuddyphd',
    'okkamuretardi',
    'OpenSignups',
    'opensource',
    'openstreetmap',
    'Parkour',
    'parrots',
    'PartyParrot',
    'PBSOD',
    'photography',
    'plural_irl',
    'PornhubComments',
    'postapocalyptic',
    'privacy',
    'programming',
    'programminghorror',
    'Python',
    'QueerVexillology',
    'raspberry_pi',
    'RASPBERRY_PI_PROJECTS',
    'rccars',
    'rept_irl',
    'reptiles',
    'Roadcam',
    'RTLSDR',
    'rust',
    'SampleSize',
    'saunamietteet',
    'ScarySigns',
    'SCP',
    'SCPDeclassified',
    'SelfAwarewolves',
    'selfhosted',
    'ServerPorn',
    'sfwtransformation',
    'shiey',
    'ShitAmericansSay',
    'shittygamedetails',
    'shittymoviedetails',
    'shittyprogramming',
    'Sizz',
    'Snek',
    'Sneks',
    'snowleopards',
    'space',
    'specializedtools',
    'speedrun',
    'spiderbro',
    'Steam',
    'stopperpacks',
    'Suomi',
    'Superbowl',
    'surrealism',
    'surrealmemes',
    'surrealtraa',
    'sysadmin',
    'tarantulas',
    'technicalminecraft',
    'techsupportgore',
    'techsupportmacgyver',
    'techwearclothing',
    'tf_irl',
    'The10thDentist',
    'theocho',
    'tiltshift',
    'tilwtf',
    'ToiletPaperUSA',
    'tokipona',
    'TooAfraidToAsk',
    'traaaaaaainnnnnnnnnns',
    'traaaaaaannnnnnnnnns',
    'transfurs',
    'TransSocialism',
    'trollscience',
    'trucksim',
    'truegaming',
    'TrueOffMyChest',
    'TVDetails',
    'Undertale',
    'UnethicalLifeProTips',
    'unixporn',
    'unixsocks',
    'UnresolvedMysteries',
    'uptimeporn',
    'urbanexploration',
    'UsabilityPorn',
    'VAC_Porn',
    'vexillology',
    'vexillologycirclejerk',
    'VuvuzelaIPhone',
    'watchbirdsdieinside',
    'watchpeoplesurvive',
    'Wellworn',
    'Wendigofuckers',
    'whatisthisthing',
    'wine_gaming',
    'WorkReform',
    'worldbuilding',
    'worldnews',
    'WTF',
    'WynnCraft',
    'yayfoxxo',
    'Yeen_irl',
    'YouShouldKnow'
]